#!/data/data/com.termux/files/usr/bin/bash

MODULES_DIR="modules"
OUTPUT="modules-list.js"
PRIORITY_FILE="priority.txt"

echo "// Auto-generated by generate-priority.sh" > $OUTPUT
echo "window.MODULES = [" >> $OUTPUT

if [ ! -f "$PRIORITY_FILE" ]; then
    echo "Error: priority.txt not found"
    exit 1
fi

while IFS= read -r mod; do
    [ -z "$mod" ] && continue
    folder="$MODULES_DIR/$mod"
    if [ -d "$folder" ]; then
        if [ -f "$folder/module.json" ]; then
            name=$(grep -o '"name": *"[^"]*"' "$folder/module.json" | cut -d'"' -f4)
            icon=$(grep -o '"icon": *"[^"]*"' "$folder/module.json" | cut -d'"' -f4)
            desc=$(grep -o '"description": *"[^"]*"' "$folder/module.json" | cut -d'"' -f4)
        else
            name="$mod"
            icon="fa-folder"
            desc=""
        fi
        echo "  { id: '$mod', name: '$name', icon: '$icon', description: '$desc' }," >> $OUTPUT
    else
        echo "  // Warning: module '$mod' not found" >> $OUTPUT
    fi
done < "$PRIORITY_FILE"

echo "];" >> $OUTPUT
echo "Generated $OUTPUT with priority list"
