// Auto-generated by generate-priority.sh
window.MODULES = [
  { id: 'stok', name: 'Stok Management', icon: 'fa-boxes', description: 'Kelola stok barang' },
  { id: 'maintenance', name: 'maintenance', icon: 'fa-folder', description: '' },
  { id: 'sekuriti', name: 'sekuriti', icon: 'fa-folder', description: '' },
  { id: 'janitor-in', name: 'janitor-in', icon: 'fa-folder', description: '' },
  { id: 'janitor-out', name: 'janitor-out', icon: 'fa-folder', description: '' },
  { id: 'booking', name: 'booking', icon: 'fa-folder', description: '' },
  { id: 'k3', name: 'k3', icon: 'fa-folder', description: '' },
  { id: 'asset', name: 'asset', icon: 'fa-folder', description: '' },
  { id: 'commandcenter', name: 'commandcenter', icon: 'fa-folder', description: '' },
];
