#!/data/data/com.termux/files/usr/bin/bash

MODULES_DIR="modules"
OUTPUT_FILE="modules-list.js"

echo "// Auto-generated by generate-modules.sh" > $OUTPUT_FILE
echo "window.MODULES = [" >> $OUTPUT_FILE

for module in $MODULES_DIR/*/; do
    module_name=$(basename "$module")
    # Cek jika ada file module.json untuk metadata
    if [ -f "$module/module.json" ]; then
        name=$(grep -o '"name": *"[^"]*"' "$module/module.json" | cut -d'"' -f4)
        icon=$(grep -o '"icon": *"[^"]*"' "$module/module.json" | cut -d'"' -f4)
        description=$(grep -o '"description": *"[^"]*"' "$module/module.json" | cut -d'"' -f4)
    else
        name="$module_name"
        icon="fa-folder"
        description=""
    fi
    echo "  { id: '$module_name', name: '$name', icon: '$icon', description: '$description' }," >> $OUTPUT_FILE
done

echo "];" >> $OUTPUT_FILE
echo "Generated $OUTPUT_FILE"
